#!/bin/bash

#I have to clean up yum first
sudo yum clean all
#Then I will update it
sudo yum -y update
#And we have to install apache
sudo yum -y install httpd

#Another thing I have to do is add in apache to get past my firewalls etc.
#And then I will reload the firewalls
sudo firewall-cmd --permanent --add-port=80/tcp
sudo firewall-cmd --permanent --add-port=443/tcp
sudo firewall-cmd --reload

#commenting out my welcome.conf file
sudo sed -i 's/^/#/g' /etc/httpd/conf.d/welcome.conf

# Creating our index.html
sudo echo -e "<html> \n<h1> Welcome to my Capstone Project!</h1> \n</html>" > /var/www/html/index.html    

#I will enable and start my apache too
sudo systemctl enable httpd
sudo systemctl start httpd

