#!/bin/bash

yum -y install google-cloud-sdk
google-cloud-sdk-app-engine-python

gcloud init

pip install --upgrade pip
pip install oauth2client
pip install --upgrade google-api-python-client

yum install git -y

git clone https://github.com/passwordlandia/capstone.git

#This is my startup script for my load balancer, it is a work in progress.
#But I hope to have it refined by the end of the week.

##########################################################################################################################
####################################PRIVATE SERVER CODE###################################################################
##########################################################################################################################
gcloud compute networks create lbs1private-network --subnet-mode=custom

gcloud compute networks subnets create lbs1-subnet \
    --network=lbs1private-network \
    --range=10.168.0.0/24 \
    --region=us-west1-b
    
gcloud compute firewall-rules create www-firewall \
    --target-tags http-tag --allow tcp:80

gcloud compute firewall-rules create fw-allow-lbs1-subnet \
    --network=lbs1private-network \
    --action=allow \
    --direction=ingress \
    --source-ranges=10.168.0.3/24 \
    --rules=tcp,udp,icmp
    
gcloud compute firewall-rules create fw-allow-ssh \
    --network=lbs1private-network \
    --action=allow \
    --direction=ingress \
    --target-tags=allow-ssh \
    --rules=tcp:22

gcloud compute firewall-rules create fw-allow-health-check \
    --network=lbs1private-network \
    --action=allow \
    --direction=ingress \
    --target-tags=allow-health-check \
    --source-ranges=130.211.0.0/22,35.191.0.0/16 \
    --rules=tcp,udp,icmp

##########################################################################################################################

#This is my LOADBALANCER code:
gcloud compute instances create lbs1priv \
    --image-family debian-8 \
    --image-project debian-cloud \
    --tags tcp-lb \
    --zone us-west1-b \
    --metadata startup-script="#! /bin/bash
      sudo apt-get update
      sudo apt-get install apache2 -y
      sudo sed -i '/Listen 80/c\Listen 110' /etc/apache2/ports.conf
      sudo sed -i '/\/c\\' /etc/apache2/sites-enabled/000-default.conf
      sudo service apache2 restart
      echo '<!doctype html><html><body><h1>lbs1priv</h1></body></html>' | tee /var/www/html/index.html
      EOF"

lbs1ip=$(gcloud compute instances list | grep lbs1priv | awk '{ print $4 }' | tail -1)

#This is my POSTGRES server code:
gcloud compute instances create pgpriv  \
    --zone=us-us-west1-b  \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags=allow-ssh,allow-health-check,http-tag,https-tag \
    --subnet=lbs1-subnet \
    --metadata-from-file startup-script="capstone/pgpriv"
    
pgip=$(gcloud compute instances list | grep pgpriv | awk '{ print $4 }' | tail -1)

#This is my NFS server code:
gcloud compute instances create nfspriv  \
    --zone=us-us-west1-b  \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags=allow-ssh,allow-health-check,http-tag,https-tag \
    --subnet=lbs1-subnet \
    --metadata-from-file startup-script="capstone/nfspriv"
 
nfsip=$(gcloud compute instances list | grep nfspriv | awk '{ print $4 }' | tail -1)

#This is my LDAP server code:
gcloud compute instances create ldappriv  \
    --zone=us-us-west1-b  \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags=allow-ssh,allow-health-check,http-tag,https-tag \
    --subnet=lbs1-subnet \
    --metadata-from-file startup-script="capstone/ldappriv"

ldapip=$(gcloud compute instances list | grep ldappriv | awk '{ print $4 }' | tail -1)

#This is my Nagios server code:
gcloud compute instances create nagpriv  \
    --zone=us-us-west1-b  \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags=allow-ssh,allow-health-check,http-tag,https-tag \
    --subnet=lbs1-subnet \
    --metadata-from-file startup-script="capstone/nagpriv"

nagip=$(gcloud compute instances list | grep nagpriv | awk '{ print $4 }' | tail -1)

##########################################################################################################################
####################################PUBLIC SERVER CODE####################################################################
##########################################################################################################################
gcloud compute networks create lbs2pub-network --subnet-mode=custom

gcloud compute networks subnets create lbs2subnet \
    --network=lbs2pub-network \
    --range=10.168.1.0/24 \
    --region=us-west1-c

gcloud compute firewall-rules create fw-allow-lbs2-subnet \
    --network=lbs2pub-network \
    --action=allow \
    --direction=ingress \
    --source-ranges=10.168.1.2/24 \
    --rules=tcp,udp,icmp
    
gcloud compute firewall-rules create fw-allow-ssh \
    --network=lbs2pub-network \
    --action=allow \
    --direction=ingress \
    --target-tags=allow-ssh \
    --rules=tcp:22

gcloud compute firewall-rules create fw-allow-health-check \
    --network=lbs2pub-network \
    --action=allow \
    --direction=ingress \
    --target-tags=allow-health-check \
    --source-ranges=130.211.0.0/22,35.191.0.0/16 \
    --rules=tcp,udp,icmp
##########################################################################################################################
#This is my APACHE server code:
gcloud compute instances create appublic  \
    --zone=us-us-west1-c  \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags=allow-ssh,allow-health-check,http-tag,https-tag \
    --subnet=lbs2-subnet \
    --metadata-from-file startup-script="capstone/appublic"

#This is my DJANGO server 1 code:
gcloud compute instances create djpub1  \
    --zone=us-us-west1-a  \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags=allow-ssh,allow-health-check,http-tag,https-tag \
    --subnet=lbs2-subnet \
    --metadata-from-file startup-script="capstone/djpubs"

#This is my DJANGO server 2 code:
gcloud compute instances create djpub2  \
    --zone=us-us-west1-a  \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags=allow-ssh,allow-health-check,http-tag,https-tag \
    --subnet=lbs2-subnet \
    --metadata-from-file startup-script="capstone/djpubs"
   
 #This is my DJANGO server 3 code:
gcloud compute instances create djpub3  \
    --zone=us-us-west1-a  \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags=allow-ssh,allow-health-check,http-tag,https-tag \
    --subnet=lbs2-subnet \
    --metadata-from-file startup-script="capstone/djpubs"
