#!/bin/bash

#This is a readme file only. Dedicated to a greeting.

echo 

"Hello everyone!"
"This is my github page for my capstone project, where I will be adding in" 
"all of my code to help merge 10 servers and 2 routers over a private and"
"public network and this is where I will struggle. It has been nearly a year"
"since I worked with a github repository, so I will also be self teaching as"
"I go along. I will include this page on my personal website that I am creating"
"to market myself available at the link below."

######################################################################
https://jam198604.wixsite.com/josephmiller
